apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      hostPath:
        path: /tmp
        type: Directory
